[DEFAULT]
pre = setup
quiet = False
pre_user = root
user = root
timeout = 600
post_user = root
post = cleanup
outputdir = /var/tmp/test_results
tags = ['functional']


[tests/functional/rsend]
tests = ['send_encrypted_files',
    'send_encrypted_hierarchy',
    'send_encrypted_props',
    'send_encrypted_truncated_files',
    'send_freeobjects',
    'send_holds',
    'send_hole_birth',
    'send_mixed_raw',
    'send_realloc_dnode_size',
    'send_realloc_encrypted_files',
    'send_realloc_files',
    'send_spill_block']
tags = ['functional', 'rsend']
